const { v4: uuid } = require('uuid');

const id = uuid();

module.exports = {
  buyOrder: {
    id,
    refId: null,
    url: `https://api.robinhood.com/orders/${id}/`,
    account: 'https://api.robinhood.com/accounts/123456789/',
    position: `https://api.robinhood.com/positions/123456789/${id}/`,
    cancel: `https://api.robinhood.com/orders/${id}/cancel/`,
    instrument: `https://api.robinhood.com/instruments/${id}/`,
    cumulativeQuantity: 0,
    averagePrice: null,
    fees: 0,
    state: 'unconfirmed',
    type: 'market',
    side: 'buy',
    timeInForce: 'gfd',
    trigger: 'immediate',
    price: 2.78,
    stopPrice: null,
    quantity: 1,
    rejectReason: null,
    createdAt: 2020,
    updatedAt: 2020,
    lastTransactionAt: 2020,
    executions: [],
    extendedHours: false,
    overrideDtbpChecks: false,
    overrideDayTradeChecks: false,
    responseCategory: null,
    stopTriggeredAt: null,
    lastTrailPrice: null,
    lastTrailPriceUpdatedAt: null,
    dollarBasedAmount: null,
    dripDividendId: null,
    totalNotional: { amount: 2.78, currencyCode: 'USD', currencyId: 1072 },
    executedNotional: null,
    investmentScheduleId: null,
  },
  sellOrder: {
    id,
    refId: null,
    url: `https://api.robinhood.com/orders/${id}/`,
    account: 'https://api.robinhood.com/accounts/123456789/',
    position: `https://api.robinhood.com/positions/123456789/${id}/`,
    cancel: `https://api.robinhood.com/orders/${id}/cancel/`,
    instrument: `https://api.robinhood.com/instruments/${id}/`,
    cumulativeQuantity: 0,
    averagePrice: null,
    fees: 0,
    state: 'unconfirmed',
    type: 'limit',
    side: 'sell',
    timeInForce: 'gtc',
    trigger: 'stop',
    price: 2.78,
    stopPrice: 2.5,
    quantity: 1,
    rejectReason: null,
    createdAt: 2020,
    updatedAt: 2020,
    lastTransactionAt: 2020,
    executions: [],
    extendedHours: false,
    overrideDtbpChecks: true,
    overrideDayTradeChecks: true,
    responseCategory: null,
    stopTriggeredAt: null,
    lastTrailPrice: null,
    lastTrailPriceUpdatedAt: null,
    dollarBasedAmount: null,
    dripDividendId: null,
    totalNotional: { amount: 2.78, currencyCode: 'USD', currencyId: 1072 },
    executedNotional: null,
    investmentScheduleId: null,
  },
};
