const { v4: uuid } = require('uuid');

const id = uuid();

module.exports = {
  id,
  ref_id: null,
  url: `https://api.robinhood.com/orders/${id}/`,
  account: 'https://api.robinhood.com/accounts/123456789/',
  position: `https://api.robinhood.com/positions/123456789/${id}/`,
  cancel: `https://api.robinhood.com/orders/${id}/cancel/`,
  instrument: `https://api.robinhood.com/instruments/${id}/`,
  cumulative_quantity: '0.00000000',
  average_price: null,
  fees: '0.00',
  state: 'unconfirmed',
  type: 'market',
  side: 'buy',
  time_in_force: 'gfd',
  trigger: 'immediate',
  price: '13.07000000',
  stop_price: null,
  quantity: '1.00000000',
  reject_reason: null,
  created_at: '2020-06-25T17:05:26.473935Z',
  updated_at: '2020-06-25T17:05:26.534210Z',
  last_transaction_at: '2020-06-25T17:05:26.473935Z',
  executions: [],
  extended_hours: false,
  override_dtbp_checks: false,
  override_day_trade_checks: false,
  response_category: null,
  stop_triggered_at: null,
  last_trail_price: null,
  last_trail_price_updated_at: null,
  dollar_based_amount: null,
  drip_dividend_id: null,
  total_notional: {
    amount: '13.07',
    currency_code: 'USD',
    currency_id: id,
  },
  executed_notional: null,
  investment_schedule_id: null,
};
