module.exports = [
  { id: '100-most-popular', name: '100 Most Popular' },
  { id: 'upcoming-earnings', name: 'Upcoming Earnings' },
  { id: 'new-on-robinhood', name: 'New On Robinhood' },
  { id: 'technology', name: 'Technology' },
  { id: 'oil-and-gas', name: 'Oil and Gas' },
  { id: 'finance', name: 'Finance' },
  { id: 'software-service', name: 'Software Service' },
  { id: 'energy', name: 'Energy' },
  { id: 'manufacturing', name: 'Manufacturing' },
  { id: 'consumer-product', name: 'Consumer Products' },
  { id: 'etf', name: 'ETF' },
  { id: 'video-game', name: 'Video Games' },
  { id: 'social-media', name: 'Social Media' },
  { id: 'health', name: 'Health' },
  { id: 'entertainment', name: 'Entertainment' },
  { id: 'internet', name: 'Internet' },
  { id: 'electronics', name: 'Electronics' },
  { id: 'semiconductor', name: 'Semiconductors' },
  { id: 'pharmaceutical', name: 'Pharmaceutical' },
  { id: 'retail', name: 'Retail' },
  { id: 'automotive', name: 'Automotive' },
  { id: 'reit', name: 'REIT' },
  { id: 'banking', name: 'Banking' },
  { id: 'food', name: 'Food' },
  { id: 'material', name: 'Materials' },
  { id: 'aerospace', name: 'Aerospace' },
];
