#!/usr/bin/env node
const fs = require('fs-extra');
const path = require('path');
const cp = require('child_process');

const apiFiles = ['robinhood', 'screeners', 'scrapers'];

const exec = (cmd) => cp.execSync(cmd).toString().trim();
const createDocsFile = (file) => {
  const input = path.resolve(__dirname, `../lib/${file}/index.js`);
  const output = path.resolve(__dirname, `../docs/api/${file}.md`);
  if (!fs.existsSync(input)) return;
  const content = exec(`npx jsdoc2md ${input}`)
    .replace(/\n#/g, '\n');
  fs.writeFileSync(output, content);
};

apiFiles.forEach(createDocsFile);
