#!/usr/bin/env node
const fs = require('fs-extra');
const path = require('path');
const jsdoc2md = require('jsdoc-to-markdown');
const cp = require('child_process');

const exec = (cmd) => cp.execSync(cmd).toString().trim();

const createApiDocs = async (pkg) => {
  console.log('creating api docs for', pkg);

  const markdown = jsdoc2md.renderSync({
    files: [
      path.resolve(__dirname, '../packages', pkg, 'lib/**/*.js'),
      path.resolve(__dirname, '../packages', pkg, 'index.js'),
      // path.resolve(__dirname, '../typedef/**/*.js'),
    ],
  });
  if (!markdown.trim()) {
    return;
  }

  const output = path.resolve('packages', pkg, 'docs/api.md');
  const docsFolder = path.resolve(__dirname, '../packages', pkg, 'docs');
  if (!fs.existsSync(docsFolder)) {
    fs.mkdirpSync(docsFolder);
  }
  const content = `# @stonksjs/${pkg} API Documentation

${markdown}`;
  fs.writeFileSync(output, content);
  const cmd = `npx prettier --write ${output}`;
  exec(cmd);
};

const packages = fs.readdirSync(path.resolve(__dirname, '../packages'));
packages.forEach((pkg) => {
  createApiDocs(pkg);
});
