#!/usr/bin/env bash
set -e

export CI='true'
# COMMIT_MESSAGE="${1}"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$CURRENT_BRANCH" != 'main' ]; then
  echo 'Not on branch main'
  exit 1
fi

# if [ -z "$COMMIT_MESSAGE" ]; then
#   echo 'Commit message empty'
#   exit 1
# fi

# git add .
# git commit -m "$COMMIT_MESSAGE" --allow-empty

# follow prompts to release on npm and github
npx lerna publish
npm version from-git --allow-same-version
version=$(git describe --abbrev=0)
gh release create "$version" --generate-notes
